/*
Copyright (c) 2019 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.game.postprocrenderer;

import dlib.core.memory;
import dlib.core.ownership;

import dagon.core.event;
import dagon.core.time;
import dagon.resource.scene;
import dagon.render.stage;
import dagon.render.deferred;
import dagon.render.framebuffer;
import dagon.render.framebuffer_rgba8;
import dagon.postproc.filterstage;
import dagon.postproc.presentstage;
import dagon.postproc.shaders.tonemap;
import dagon.postproc.shaders.fxaa;
import dagon.game.renderer;

class PostProcRenderer: Renderer
{
    Framebuffer inputBuffer;
    Framebuffer outputBuffer;
    PresentStage stagePresent;
    
    Framebuffer pingPongBuffer1;
    Framebuffer pingPongBuffer2;
    
    TonemapShader tonemapShader;
    FXAAShader fxaaShader;
    
    Tonemapper tonemapper = Tonemapper.ACES;
    float exposure = 1.0f;
    
    this(EventManager eventManager, Framebuffer inputBuffer, Owner owner)
    {
        super(eventManager, owner);
        
        this.inputBuffer = inputBuffer;
        
        pingPongBuffer1 = New!FramebufferRGBA8(view.width, view.height, this);
        pingPongBuffer2 = New!FramebufferRGBA8(view.width, view.height, this);
        
        tonemapShader = New!TonemapShader(this);
        auto stageTonemap = New!FilterStage(pipeline, tonemapShader);
        stageTonemap.view = view;
        stageTonemap.inputBuffer = inputBuffer;
        stageTonemap.outputBuffer = pingPongBuffer1;
        
        fxaaShader = New!FXAAShader(this);
        auto stageFXAA = New!FilterStage(pipeline, fxaaShader);
        stageFXAA.view = view;
        stageFXAA.inputBuffer = pingPongBuffer1;
        stageFXAA.outputBuffer = pingPongBuffer2;
        
        outputBuffer = pingPongBuffer2;
    }
    
    override void update(Time t)
    {
        super.update(t);
        
        tonemapShader.tonemapper = tonemapper;
        tonemapShader.exposure = exposure;
    }
    
    override void setViewport(uint x, uint y, uint w, uint h)
    {
        super.setViewport(x, y, w, h);
        
        pingPongBuffer1.resize(view.width, view.height);
        pingPongBuffer2.resize(view.width, view.height);
    }
}
