/*
Copyright (c) 2019 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.resource.dds;

import std.stdio;
import std.file;

import dlib.core.memory;
import dlib.core.stream;
import dlib.core.compound;
import dlib.image.color;
import dlib.image.image;
import dlib.image.io.utils;

import dagon.graphics.compressedimage;

//version = DDSPDebug;

struct DDPixelFormat
{
    uint size;
    uint flags;
    uint fourCC;
    uint bpp;
    uint redMask;
    uint greenMask;
    uint blueMask;
    uint alphaMask;
}

struct DDSCaps
{
    uint caps;
    uint caps2;
    uint caps3;
    uint caps4;
}

struct DDColorKey
{
    uint lowVal;
    uint highVal;
}

struct DDSurfaceDesc
{
    uint size;
    uint flags;
    uint height;
    uint width;
    uint pitch;
    uint depth;
    uint mipMapLevels;
    uint alphaBitDepth;
    uint reserved;
    uint surface;

    DDColorKey ckDestOverlay;
    DDColorKey ckDestBlt;
    DDColorKey ckSrcOverlay;
    DDColorKey ckSrcBlt;

    DDPixelFormat format;
    DDSCaps caps;

    uint textureStage;
}

uint makeFourCC(char ch0, char ch1, char ch2, char ch3)
{
    return
        ((cast(uint)ch3 << 24) & 0xFF000000) |
        ((cast(uint)ch2 << 16) & 0x00FF0000) |
        ((cast(uint)ch1 << 8)  & 0x0000FF00) |
        ((cast(uint)ch0)       & 0x000000FF);
}

enum FOURCC_DXT1 = makeFourCC('D', 'X', 'T', '1');
enum FOURCC_DXT3 = makeFourCC('D', 'X', 'T', '3');
enum FOURCC_DXT5 = makeFourCC('D', 'X', 'T', '5');

Compound!(CompressedImage, string) loadDDS(InputStream istrm)
{
    CompressedImage img = null;
    
    void finalize()
    {
    }
    
    Compound!(CompressedImage, string) error(string errorMsg)
    {
        finalize();
        if (img)
        {
            Delete(img);
            img = null;
        }
        return compound(img, errorMsg);
    }
    
    char[4] magic;
    
    if (!istrm.fillArray(magic))
    {
        return error("loadDDS error: not a DDS file or corrupt data");
    }
    
    version(DDSPDebug)
    {
        writeln("Signature: ", magic);
    }

    if (magic != "DDS ")
    {
        return error("loadDDS error: not a DDS file");
    }
    
    DDSurfaceDesc surfaceDesc = readStruct!DDSurfaceDesc(istrm);
    
    version(DDSPDebug)
    {
        writeln("surfaceDesc.size: ", surfaceDesc.size);
        writeln("surfaceDesc.flags: ", surfaceDesc.flags);
        writeln("surfaceDesc.height: ", surfaceDesc.height);
        writeln("surfaceDesc.width: ", surfaceDesc.width);
        writeln("surfaceDesc.pitch: ", surfaceDesc.pitch);
        writeln("surfaceDesc.depth: ", surfaceDesc.depth);
        writeln("surfaceDesc.mipMapLevels: ", surfaceDesc.mipMapLevels);
        writeln("surfaceDesc.alphaBitDepth: ", surfaceDesc.alphaBitDepth);
        writeln("surfaceDesc.reserved: ", surfaceDesc.reserved);
        writeln("surfaceDesc.surface: ", surfaceDesc.surface);
        
        writeln("surfaceDesc.ckDestOverlay.lowVal: ", surfaceDesc.ckDestOverlay.lowVal);
        writeln("surfaceDesc.ckDestOverlay.highVal: ", surfaceDesc.ckDestOverlay.highVal);
        writeln("surfaceDesc.ckDestBlt.lowVal: ", surfaceDesc.ckDestBlt.lowVal);
        writeln("surfaceDesc.ckDestBlt.highVal: ", surfaceDesc.ckDestBlt.highVal);
        writeln("surfaceDesc.ckSrcOverlay.lowVal: ", surfaceDesc.ckSrcOverlay.lowVal);
        writeln("surfaceDesc.ckSrcOverlay.highVal: ", surfaceDesc.ckSrcOverlay.highVal);
        writeln("surfaceDesc.ckSrcBlt.lowVal: ", surfaceDesc.ckSrcBlt.lowVal);
        writeln("surfaceDesc.ckSrcBlt.highVal: ", surfaceDesc.ckSrcBlt.highVal);
        
        writeln("surfaceDesc.format.size: ", surfaceDesc.format.size);
        writeln("surfaceDesc.format.flags: ", surfaceDesc.format.flags);
        writeln("surfaceDesc.format.fourCC: ", surfaceDesc.format.fourCC);
        writeln("surfaceDesc.format.bpp: ", surfaceDesc.format.bpp);
        writeln("surfaceDesc.format.redMask: ", surfaceDesc.format.redMask);
        writeln("surfaceDesc.format.greenMask: ", surfaceDesc.format.greenMask);
        writeln("surfaceDesc.format.blueMask: ", surfaceDesc.format.blueMask);
        writeln("surfaceDesc.format.alphaMask: ", surfaceDesc.format.alphaMask);
        
        writeln("surfaceDesc.caps.caps: ", surfaceDesc.caps.caps);
        writeln("surfaceDesc.caps.caps2: ", surfaceDesc.caps.caps2);
        writeln("surfaceDesc.caps.caps3: ", surfaceDesc.caps.caps3);
        writeln("surfaceDesc.caps.caps4: ", surfaceDesc.caps.caps4);
        
        writeln("surfaceDesc.textureStage: ", surfaceDesc.textureStage);
    }
    
    CompressedImageFormat format;
    switch(surfaceDesc.format.fourCC)
    {
        case FOURCC_DXT1:
            version(DDSPDebug) writeln("FOURCC_DXT1");
            format = CompressedImageFormat.S3TC_DXT1;
            break;
        case FOURCC_DXT3:
            version(DDSPDebug) writeln("FOURCC_DXT3");
            format = CompressedImageFormat.S3TC_DXT3;
            break;
        case FOURCC_DXT5:
            version(DDSPDebug) writeln("FOURCC_DXT5");
            format = CompressedImageFormat.S3TC_DXT5;
            break;
        default:
            return error("loadDDS error: unsupported compression type");
    }
    
    size_t bufferSize = cast(size_t)(istrm.size - istrm.getPosition);
    version(DDSPDebug) writeln("bufferSize: ", bufferSize);
    
    img = New!CompressedImage(surfaceDesc.width, surfaceDesc.height, format, surfaceDesc.mipMapLevels, bufferSize);
    istrm.readBytes(img.data.ptr, bufferSize);
    
    return compound(img, "");
}
