/*
Copyright (c) 2019 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dagon.resource.scene;

import std.path;

import dlib.core.memory;
import dlib.core.ownership;
import dagon.core.application;
import dagon.core.bindings;
import dagon.core.event;
import dagon.core.time;
import dagon.graphics.entity;
import dagon.resource.asset;
import dagon.resource.obj;
import dagon.resource.image;
import dagon.resource.texture;

class Scene: EventListener
{
    Application application;
    AssetManager assetManager;
    EntityManager entityManager;
    EntityGroupSpatial spatial;
    EntityGroupHUD hud;
    bool isLoading = false;
    bool loaded = false;
    
    this(Application application)
    {
        super(application.eventManager, application);
        this.application = application;
        entityManager = New!EntityManager(this);
        spatial = New!EntityGroupSpatial(entityManager, this);
        hud = New!EntityGroupHUD(entityManager, this);
        
        assetManager = New!AssetManager(eventManager, this);
        beforeLoad();
        isLoading = true;
        assetManager.loadThreadSafePart();
    }
    
    // Set preload to true if you want to load the asset immediately
    // before actual loading (e.g., to render a loading screen)
    Asset addAsset(Asset asset, string filename, bool preload = false)
    {
        if (preload)
            assetManager.preloadAsset(asset, filename);
        else
            assetManager.addAsset(asset, filename);
        return asset;
    }
    
    ImageAsset addImageAsset(string filename, bool preload = false)
    {
        ImageAsset img;
        if (assetManager.assetExists(filename))
            img = cast(ImageAsset)assetManager.getAsset(filename);
        else
        {
            img = New!ImageAsset(assetManager.imageFactory, assetManager.hdrImageFactory, assetManager);
            addAsset(img, filename, preload);
        }
        return img;
    }
    
    TextureAsset addTextureAsset(string filename, bool preload = false)
    {
        TextureAsset tex;
        if (assetManager.assetExists(filename))
            tex = cast(TextureAsset)assetManager.getAsset(filename);
        else
        {
            tex = New!TextureAsset(assetManager.imageFactory, assetManager.hdrImageFactory, assetManager);
            addAsset(tex, filename, preload);
        }
        return tex;
    }
    
    T add(T)(string filename, bool preload = false)
    {
        T asset;
        if (assetManager.assetExists(filename))
            asset = cast(T)assetManager.getAsset(filename);
        else
        {
            asset = New!T(assetManager);
            addAsset(asset, filename, preload);
        }
        return asset;
    }
    
    auto add(string filename)(bool preload = false)
    {
        enum string ext = extension(filename);
        static if (ext == ".obj")
        {
            return add!OBJAsset(filename, preload);
        }
        else static if (
            ext == ".png" || ext == ".PNG" ||
            ext == ".jpg" || ext == ".JPG" || 
            ext == ".jpeg" || ext == ".JPEG" ||
            ext == ".tga" || ext == ".TGA" || 
            ext == ".bmp" || ext == ".BMP" || 
            ext == ".hdr" || ext == ".HDR")
        {
            return addTextureAsset(filename, preload);
        }
        else
        {
            // TODO: generic file asset
            static assert(0, "Unknown file type: " ~ filename);
        }
    }
    
    // Override me
    void beforeLoad()
    {
    }
    
    // Override me
    void onLoad(Time t, float progress)
    {
    }
    
    // Override me
    void afterLoad()
    {
        
    }
    
    // Override me
    void onUpdate(Time t)
    {
    }
    
    import std.stdio;
    
    void update(Time t)
    {        
        if (isLoading)
        {
            onLoad(t, assetManager.nextLoadingPercentage);
            isLoading = assetManager.isLoading;
        }
        else
        {
            if (!loaded)
            {
                assetManager.loadThreadUnsafePart();
                writeln("Loaded");
                loaded = true;
                afterLoad();
            }
            
            processEvents();
            
            onUpdate(t);
            
            foreach(e; entityManager.entities)
            {
                e.update(t);
            }
        }
    }
}

class EntityGroupSpatial: Owner, EntityGroup
{
    EntityManager entityManager;

    this(EntityManager entityManager, Owner owner)
    {
        super(owner);
        this.entityManager = entityManager;
    }

    int opApply(scope int delegate(Entity) dg)
    {
        int res = 0;
        auto entities = entityManager.entities.data;
        for(size_t i = 0; i < entities.length; i++)
        {
            auto e = entities[i];
            if (e.layer >= 0)
            {
                res = dg(e);
                if (res)
                    break;
            }
        }
        return res;
    }
}

class EntityGroupHUD: Owner, EntityGroup
{
    EntityManager entityManager;

    this(EntityManager entityManager, Owner owner)
    {
        super(owner);
        this.entityManager = entityManager;
    }

    int opApply(scope int delegate(Entity) dg)
    {
        int res = 0;
        auto entities = entityManager.entities.data;
        for(size_t i = 0; i < entities.length; i++)
        {
            auto e = entities[i];
            if (e.layer < 0)
            {
                res = dg(e);
                if (res)
                    break;
            }
        }
        return res;
    }
}
